### ISSUE TITLE
Doesn't seems to work

### ISSUE THREAD

**Issue by fdalfa** [kkthxbye-code/netbox-old-search#1]
Ciao,

I tried it on a 3.5.8 netbox and it doesn't seems to work. Here the plugin config
`PLUGINS_CONFIG = {
    "netbox_old_search": {
        "replace_search": False, # Hijacks the top search bar in netbox, redirecting to this plugins search method instead
        "show_menu": True # Shows a link to the old search form in the plugin menu
    }
}` I see the link in the plugin menu but the search functionality still seem the new one
![immagine](https://github.com/kkthxbye-code/netbox-old-search/assets/56688519/aacb0f10-64b9-4ed4-bdd4-a6eefdeb60b8)
where am I wrong?

thanks and regards,
Fabrizio

**Comment by kkthxbye-code** [comment]
When clicking the Old Search link, what URL are you taken to and how does it look?

You sure you are not using the top search bar? That requires setting `replace_search` to `True`, which you have set to `False` currently.

**Comment by fdalfa** [comment]
Ciao!

> When clicking the Old Search link, what URL are you taken to and how does it look?

netbox/plugins/old-search/search/ and it shows the plugin's search
![immagine](https://github.com/kkthxbye-code/netbox-old-search/assets/56688519/3d74a7d3-4aa4-41e7-a981-5051ec08c2ee)
but the search action bring me to the new global search netbox/search/?q=371; if I try manually the plugin's url netbox/plugins/old-search/search/?q=371 it works like a charm
![immagine](https://github.com/kkthxbye-code/netbox-old-search/assets/56688519/40867625-9706-460f-83c8-6e4b11382157)

I'd like to don't replace the global search and have the option to use the old search in the plugin menu.

thanks and regards,
Fabrizio

**Comment by kkthxbye-code** [comment]
Ahh gotcha, I'll check it out.

**Comment by kkthxbye-code** [comment]
I release v0.1.3 with a fix, could you try that out?

**Comment by fdalfa** [comment]
ciao!

I tried and it works!

thansk and regards
Fabrizio
